on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: |
          curl -f#SL --compressed --tlsv1.2 https://api.cirrus-ci.com/v1/artifact/github/danielhuang/cotton/Build/binaries/target/x86_64-unknown-linux-gnu/release/cotton > /usr/local/bin/cotton
          chmod +x /usr/local/bin/cotton
      - run: cotton run test
      - run: cotton run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}